version: '2'
services:
  kafka:
    # https://github.com/lensesio/fast-data-dev
    image: landoop/fast-data-dev
    container_name: kafka-local
    ports:
      - "9092:9092"
      - "8081:8081"
      - "8082:8082"
      - "8083:8083"
      - "2181:2181"
      - "3030:3030"
      - "3031:3031"
    environment:
      ADV_HOST: kafka
  magic:
    image: digitsy/kafka-magic
    container_name: kafka-magic-local
    ports:
      - "8080:80"
    volumes:
      - ./config:/config
    environment:
      # KMAGIC_ALLOW_TOPIC_DELETE: "true"
      KMAGIC_CONFIG_STORE_TYPE: "file"
      KMAGIC_CONFIG_STORE_CONNECTION: "Data Source=/config/KafkaMagicConfig.db;"
      KMAGIC_CONFIG_ENCRYPTION_KEY: "123456aA"


# ports:
#   - "9092:9092"   Broker/Bootstrap server
#   - "8081:8081"   Schema registry
#   - "8082:8082"   Kafka REST proxy
#   - "8083:8083"   Kafka connect distributed
#   - "2181:2181"   Zookeeper
#   - "3030:3030"   Web server
#   - "3031:3031"   ??
